"""empty message

Revision ID: 0f81c470f82a
Revises: 4c08a08cf8b1
Create Date: 2023-11-17 14:53:51.065448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f81c470f82a'
down_revision = '4c08a08cf8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filmes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filmes', schema=None) as batch_op:
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
