"""empty message

Revision ID: e23b602385dc
Revises: c6170d768183
Create Date: 2023-11-22 09:27:40.970595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23b602385dc'
down_revision = 'c6170d768183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filmes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filmes', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
